### ISSUE TITLE
[documentation] Предложение добавить лицензию

### ISSUE THREAD

**Issue by ghost** [tmoeg-Vladivostok/site-markdown#4]
Я предлагаю добавить лицензию для этого репозитория, так как на любое ПО/работу без лицензии по умолчанию распространяется авторское право

<details>
<summary><a href="https://www.gnu.org/licenses/license-list.ru.html#NoLicense">Цитата</a> от GNU</summary>
<blockquote>Некоторые разработчики думают, что программа без лицензии автоматически попадает в <a href="https://www.gnu.org/licenses/license-list.ru.html#PublicDomain">общественное достояние</a>. При нынешнем авторском праве это не так; наоборот, оно по умолчанию распространяется на все произведения, на какие только может. В том числе на программы. При отсутствии лицензии, которая дает пользователям свободу, у них нет никакой свободы. В некоторых странах пользователи, которые берут из сети программу без лицензии, могут нарушать авторское право уже тем, что компилируют или выполняют ее.</blockquote>
</details>

<details>
<summary>Как легко выбрать лицензию</summary>
<img src="https://github.com/user-attachments/assets/ca652e1a-369e-4774-90f9-b3707a8a3253" alt="">
<i>P.S.: составлял сам, если что-то непонятно, пните</i>
</details>

*Поставьте 👍, если считаете, что этот issue считается важным*

**Comment by Aserogl31** [comment]
я слепой, в репе и так была лицензия

**Comment by ghost** [comment]
а, я слепой, в репе и так была лицензия
